export default {
    categoryOpt: [{
        label: '家用电器',
        value: 1
    }, {
        label: '手机数码',
        value: 2
    }, {
        label: '电脑办公',
        value: 3
    }, {
        label: '家居厨具',
        value: 4
    }, {
        label: '服饰鞋品',
        value: 5
    }, {
        label: '美妆',
        value: 6
    }, {
        label: '母婴用品',
        value: 7
    }, {
        label: '玩具乐器',
        value: 8
    }, {
        label: '食品饮料',
        value: 9
    }, {
        label: '医药保健',
        value: 10
    }, {
        label: '图书',
        value: 11
    }, ]
}